spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
    platform: mysql
  jms:
    template:
      default-destination: customers
      receive-timeout: 5000
  activemq:
    packages:
      trust-all: true